### ISSUE TITLE
Color: change threshold `0.00313` to `0.003131`

### ISSUE THREAD

**Issue by chharvey** [chharvey/extrajs-types#1]
In the function `_sRGB_Linear`, the threshold `0.04045` was taken from https://github.com/w3c/wcag/issues/360#issuecomment-419199254 and has four significant figures.

In the inverse function `_linear_sRGB`, the threshold `0.00313` only has three sig figs, but it should should have the same number of sig figs as that in its inverse.

Therefore [it should be changed to `0.003131`](https://github.com/chharvey/extrajs-types/commit/728a48352084eddf19df3eb72114961ebd2dfe00#commitcomment-34256032).

https://github.com/chharvey/extrajs-types/blob/728a48352084eddf19df3eb72114961ebd2dfe00/src/class/Color.class.ts#L171-L174

https://github.com/chharvey/extrajs-types/blob/728a48352084eddf19df3eb72114961ebd2dfe00/src/class/Color.class.ts#L184-L187

**Comment by Myndex** [comment]
No, it should be changed to **0.0031308** because _that_ is the _standard_. 

See IEC 61966-2-1:1999, the relevant international standard. The WCAG is not the standard for sRGB.

Regards,

Andy

**Comment by chharvey** [comment]
@Myndex  can you provide a link?

**Comment by Myndex** [comment]
Hi @chharvey 

Yes, the official IEC standard is a paid for doc, but I do have a link for the pre-published standard:

The **1998 draft** of the IEC standard: http://www.photo-lovers.org/pdf/color/srgb.pdf

The **official IEC document** for purchase: https://webstore.iec.ch/publication/6169

The **sRGB Wikipedia page**: https://en.wikipedia.org/wiki/SRGB

The **ITU reference** (see page 13): https://www.itu.int/dms_pub/itu-r/opb/rep/R-REP-BT.2380-2015-PDF-E.pdf

**Bruce Lindbloom's** site of math for colorspaces: http://www.brucelindbloom.com

The **ICC's paper on sRGB**: http://www.color.org/sRGB.pdf

And I also recommend Charles Poynton's **Gamma FAQ**:  https://poynton.ca/GammaFAQ.html

Please let me know fi you have any questions.

Andy
